import logging as log

LAYOUT_WIDTH = 128
LAYOUT_HEIGHT = 128
LAYOUT_PERTURB = 0.8

NETWORK_NUM_NODE = 16
NETWORK_MIN_RANGE = 1

NODE_DATA_MAX = 1000

ALGORITHM_MAX_ROUND = 1000
ALGORITHM_TIMEOUT_THRESHOLD = 5
ALGORITHM_MAX_COMPLETION = 8

UI_DRAW = True

LOG_LEVEL = log.ERROR

RADIO_OFF = 0
RADIO_ON = 1
RADIO_ALL = -1

RADIO_POWER = 128

DEFAULT_RADIO = {0: 32, 1: 96}

UI_EDGE_COLOR = {0: 'k', 1: 'b'}
